pipeline {
  agent any

  stages {
    stage('Configure') {
      steps {
        echo 'Configure'
//
//        sh '''
//          cp ./.env.template ./.env
//          sed -i "/COMPOSE_PROJECT_NAME=/ s/=.*/=$COMPOSE_PROJECT_NAME/" ./.env
//          sed -i "/SERVICE_DOMAIN=/ s/=.*/=$SERVICE_DOMAIN/" ./.env
//          sed -i "/SERVICE_DOMAIN_EMAIL=/ s/=.*/=$SERVICE_DOMAIN_EMAIL/" ./.env
//          sed -i "/SERVICE_ID=/ s/=.*/=$SERVICE_ID/" ./.env
//          sed -i "/SERVICE_DESC=/ s/=.*/=\\"$SERVICE_DESC\\"/" ./.env
//          cat ./.env
//        '''
//
      }
    }
    stage('Build') {
      steps {
        echo 'Build'
//        sh './service-build.sh'
      }
    }
    stage('Test') {
      steps {
        echo 'Test'
//        sh './service-test.sh'
      }
    }
    stage('Up service') {
      steps {
        echo 'Up service'
//        sh './service-up.sh -d'
      }
    }
    stage('Deploy & Publish') {
      steps {
        echo 'Deploy & Publish'
//        sh './service-deploy.sh'
//        archiveArtifacts artifacts: 'mobile/platforms/android/build/outputs/apk/*.apk'
      }
    }
    stage('Cleanup') {
      steps {
        echo 'Cleanup'
      }
    }
  }
}
